all: 
  hosts:
    web01:
      ansible_host: 127.0.0.1
      ansible_user: hung
      ansible_password: hung1601
      ansible_python_interpreter: /usr/bin/python3
children:
  webservers:
    hosts:
      web01: